# Last updated on 17 January 2026 at 23:48 GMT+3
# This file is a template for custom new localizations. It's unused in game and any changes made made here here won't persist after re-generation.

[R:Stats]
# Important! Stat entries should be as short as possible.
# Total damage taken as Big Dog
Uniq13=DAMAGE TAKEN
# Skeleton's Blood gamble luck streak
Uniq14=LUCK STREAK
# Amount of gas produced by Frog
Uniq15=GAS VOLUMES

[R:HUD]
PickUpAction=PICK UP

[Bosses]
# "GUN GOD's" name isn't translated in the base game as of right now
GunGod="GUN#GOD"

[R:GameOver]
Results=RESULTS

[R:Unlock]
GenericRace="@w% UNLOCKED#@s%"
GenericSkin="@w% %-SKIN UNLOCKED#@s%"
Cheats="@wCHEATS UNLOCKED#@sCHECK OUT THE MAIN MENU SETTINGS!"

[R:Tips]
ContinuedRun=welcome back!

[Weapons]
# Electric Guitar isn't translated in the basegame as of right now
128:Name=ELECTRIC GUITAR
# Electric Guitar also uses the same description as the regular Guitar. NTM simply just adds a little sprinkle of detail to it
128:Text=fish can rock and roll

[R:MainMenu]
AchievementHidden=HIDDEN
Achievements=ACHIEVEMENTS
DiscordLink=JOIN OUR DISCORD!
RunHistory:daily=DAILY
RunHistory:weekly=WEEKLY
RunHistoryScoreAVG=@dSCORE AVG.
Leaderboards=LEADERBOARDS
MultiplayerTBA="MULTIPLAYER WILL BE AVAILABLE#IN FUTURE UPDATES"
CustomModeTBA="CUSTOM MODE WILL BE AVAILABLE#IN FUTURE UPDATES"
RunHistory=RUN HISTORY

[R:Intro]
LoadGameFailure=Failed to load saved run.
# The message is padded with newlines only as a stylistic choice, but automatic wordwrapping is supported.
ProjectDisclaimerText="@w###THIS IS AN UNOFFICIAL FAN-MADE RECREATION OF THE GAME.#THE DEVELOPER IS NOT AFFILIATED WITH THE ORIGINAL AUTHORS - @yVLAMBEER@w.##THIS IS A FREE AND OPEN-SOURCE GAME THAT IS DISTRIBUTED ON ITCH.IO#AND ITS SOURCE CODE IS FULLY AVAILABLE ON GITHUB.##IF YOU PAID TO GAIN ACCESS TO THIS GAME, OR WILL SEE ADS THOUGHOUT THE GAME, IT'S RECOMMENDED#THAT YOU UNINSTALL THE APPLICATION IMMEDIATELY."
ProjectDisclaimerTitle=DISCLAIMER
DisclaimerContinue=CLICK TO CONTINUE
LoadGameYes=YES
LoadGameNo=NO
LoadGameContinue=@sCONTINUE THIS SAVED RUN?@w

[ResourcepackOptions]
DisclaimerText="RESOURCEPACKS ARE AN EXCLUSIVE FEATURE OF#NUCLEAR THRONE MOBILE.##A RESOURCEPACK IS A USER-CREATED ASSET COLLECTION (TEXTURES, SOUNDS, TEXT) FOR DECORATIVE PURPOSES ONLY, WITH NO GAMEPLAY BENEFITS.##RESOURCEPACK BROWSER, DESPITE BEING MODERATED,#MAY STILL CONTAIN QUESTIONABLE CONTENT.##THE DEVELOPER IS NOT LIABLE FOR ANY HARMFUL MATERIAL."
# Delay before the user is able to proceed to resourcepack options
DisclaimerProceedWait=@sPROCEED (%)
DisclaimerProceed=@yPROCEED
ResourcepackOptions=RESOURCEPACKS
ViewInstalled=VIEW INSTALLED
Browse=BROWSE DOWNLOAD
DirectDownload=DIRECT DOWNLOAD

[Options]
CheatOptions=CHEATS
CharacterPrefOptions=CHARACTER PREFERENCES
ExperimentalOptions=EXPERIMENTAL OPTIONS
ProfileOptions=PROFILE

[AudioOptions]
SoundsVolume=EFFECTS VOLUME

[VideoOptions]
WideScreen=WIDESCREEN
Bloom=BLOOM
Particles=PARTICLES
DisplayOptions=DISPLAY SETTINGS

[GameOptions]
NativeCursor=NATIVE CURSOR
MouseLock=MOUSELOCK
PauseButton=PAUSE BUTTON
AchievementPopups="ACHIEVEMENT#POPUPS"
ProfileOptions=PROFILE

[ProfileOptions]
ColorHEX=EDIT HEX
ColorSelectorNone=NONE
ColorRed=RED
ColorGreen=GREEN
ColorBlue=BLUE
ID=ID
IDCopied=@g[COPIED]
ProfileName=PROFILE NAME
ProfileNameInput=ENTER PROFILE NAME
ColorOptions=COLOR
ColorDefault=DEFAULT
DataOptions=DATA

[DataOptions]
OptionsReset=RESET OPTIONS
ProgressReset=ERASE PROGRESS

[ControlOptions]
GamepadOn=GAMEPAD
GamepadStyle=GAMEPAD STYLE
AimAssist=AIM ASSIST
AutoAim=FULL AUTOAIM
# Allows swapping and using abilities by pressing volume buttons
VolumeControls=VOLUME CONTROLS
# Split aim & fire into two separate control elements
SplitFireControls=SPLIT AIM & FIRE
# Force player aim crosshair to be always visible
FixedSight=FIXED SIGHT
TouchControlScale=SIZE SCALE
Remap=REMAP CONTROLS
ResetTouchLayout=RESET LAYOUT
SimpleTouchControls=SIMPLIFY
ButtonFire=FIRE
ButtonActive=ACTIVE
ButtonSwap=SWAP
ButtonPick=PICK/USE
ButtonChat=CO-OP CHAT
ButtonUp=WALK UP
ButtonDown=WALK DOWN
ButtonLeft=WALK LEFT
ButtonRight=WALK RIGHT
DebugOverlay=DEBUG OVERLAY
ResetDefaults=DEFAULT PRESET

[CharacterPrefOptions]
CharacterLocked=LOCKED
AutoTelekinesis=AUTO TELEKINESIS
AutoExplosions=AUTO EXPLOSIONS
AutoSnare=AUTO SNARE
PopPopToggle=POP-POP TOGGLE
DualWieldToggle=DUAL WIELD TOGGLE
UseWeaponWhenBeaming=USE WEAPON BEAMING
SwipeBombing=SWIPE BOMBING
GambleToggle=GAMBLE TOGGLE

[ExperimentalOptions]
KeyboardMode=KEYBOARD MODE
JoystickRegions=STICK REGIONS
HideJoysticks=HIDE JOYSTICKS

[CheatOptions]
# Developer debug overlay
Console=CONSOLE
# Unlimited skill selection range
GrillerMode=GRILLER MODE
# Player gets timed out for 45sec instead of dying
Practice=PRACTICE

[R:CoopLobby]
Host=HOST GAME
RemoteAddress=REFRESH LOCAL GAMES
RemotePort=REMOTE PORT

[ResourcepackBrowser]
LoadingList=THE LIST IS LOADING...
InstallationSuccess="@g%#INSTALLED SUCCESSFULLY!##CLICK ANYHWHERE TO CONTINUE"
Installing=INSTALLING %
InformationQuerying=QUERYING REPO INFO
# Max. 8 characters
ListRatingLabel=RATING
# Max. 8 characters
ListUpdateLabel=UPDATED
# Installed resourcepack load order setting
LoadPriority=LOAD PRIORITY
SortMode=SORT
# Max. 8 characters
SortByUpdate=UPDATED
# Max. 8 characters
SortByRating=RATING
NoPacksInstalled=NO RESOURCEPACKS ARE CURRENTLY INSTALLED.
PackDisabled=DISABLED
# Should be as short as possible
UpdatedLongAgo="LONG#AGO"
NewPackPromotion=NEW!
UpdatedJustNow=JUST NOW
UpdatedToday=TODAY
UpdatedYesterday=YESTERDAY
UpdatedRecently=RECENTLY
UpdatedThisWeek="THIS#WEEK"
UpdatedDaysAgo="% D.#AGO"
ErrorMissingFiles=MISSING RESOURCEPACK FILES
FullviewOpenGitHub=SEE GITHUB PAGE
ViewNoScreenshots=@dNO SCREENSHOTS :(
FullviewPackInfo=PACK INFO
FullviewCreationInfo=CREATED ON:
FullviewLastUpdate=LAST UPDATED:
FullviewInstallationDate=INSTALLED ON:
FullviewStars=STARS:
ButtonDownload=DOWNLOAD
ButtonDisable=DISABLE
ButtonEnable=ENABLE