# Last updated on 7 January 2026 at 04:12 GMT+3

[R:Intro]
LoadGameFailure=Falhou em carregar o jogo salvo.
# The message is padded with newlines only as a stylistic choice, but automatic wordwrapping is supported.
ProjectDisclaimerText="@w###ISTO É UMA RECREAÇÃO NÃO OFICIAL DO JOGO POR FÃS.#O DESENVOLVEDOR NÃO É AFILIADO COM OS AUTORES ORIGINAIS - @yVLAMBEER@w.##ISTO É UM JOGO GRATUITO E OPEN-SOURCE QUE É DISTRIBUIDO EM ITCH.IO$E SEU CÓDIGO FONTE É COMPLETAMENTE DISPONÍVEL NO GITHUB.##SE VOCÊ PAGOU PARA GANHAR ACESSO PARA ESTE JOGO, OU VER ANÚNCIOS NO JOGO, É RECOMENDADO#QUE VOCÊ DESINSTALE O JOGO IMEDIATAMENTE."

ProjectDisclaimerTitle=AVISO
DisclaimerContinue=APERTE PARA CONTINUAR
LoadGameYes=SIM
LoadGameNo=NÃO
LoadGameContinue=@sCONTINUAR ESTE JOGO SALVO?@w

[ControlOptions]
GamepadOn=GAMEPAD
GamepadStyle=ESTILO DE GAMEPAD
AimAssist=AIM ASSIST
AutoAim=MIRA AUTOMÁTICA
# Allows swapping and using abilities by pressing volume buttons
VolumeControls=CONTROLES POR VOLUME
# Split aim & fire into two separate control elements
SplitFireControls=SEPARAR MIRAR & ATIRAR
# Force player aim crosshair to be always visible
FixedSight=MIRA FIXA
TouchControlScale=ESCALA DE TAMANHO
Remap=REMAPEAR CONTROLES
ResetTouchLayout=RESETAR LAYOUT
SimpleTouchControls=SIMPLIFICAR
ButtonFire=ATIRAR
ButtonActive=ABILIDADE
ButtonSwap=TROCAR
ButtonPick=PEGAR/USAR
ButtonChat=CHAT CO-OP
ButtonUp=ANDAR PARA CIMA
ButtonDown=ANDAR PARA BAIXO
ButtonLeft=ANDAR PARA ESQUERDA
ButtonRight=ANDAR PARA DIREITA
DebugOverlay=OVERLAY DEBUG
ResetDefaults=REDEFINIR PADRÕES

[CharacterPrefOptions]
CharacterLocked=BLOQUEADO
AutoTelekinesis=TELECINESE AUTOMÁTICA
AutoExplosions=EXPLOSÕES AUTOMÁTICA
AutoSnare=AUTO SNARE
PopPopToggle=ALTERNAR POP-POP
DualWieldToggle=ALTERNAR EMPUNHO DUPLO
UseWeaponWhenBeaming=USAR ARMA COM FEIXE
SwipeBombing=DESLIZAR PARA ATAQUE
GambleToggle=ALTERNAR APOSTA

[Weapons]
# Electric Guitar isn't translated in the basegame as of right now
128:Name=GUITARRA ELÉTRICA
# Electric Guitar also uses the same description as the regular Guitar. NTM simply just adds a little sprinkle of detail to it
128:Text=fish can rock and roll

[R:Stats]
# Important! Stat entries should be as short as possible.
# Total damage taken
Uniq13=DANO
# Blood gamble luck streak
Uniq14=SEQUÊNCIA DE SORTE
# Amount of gas produced by the character
Uniq15=GÁS GERADO

[ProfileOptions]
ColorHEX=EDITAR HEX
ColorSelectorNone=NENHUM
ColorRed=VERMELHO
ColorGreen=VERDE
ColorBlue=AZUL
ID=ID
IDCopied=@g[COPIED]
ProfileName=NOME DE PERFIL
ColorOptions=COR
ColorDefault=PADRÃO
DataOptions=DATA

[CheatOptions]
# Developer debug overlay
Console=CONSOLE
# Unlimited skill selection range
GrillerMode=MODO GRILLER
# Player gets timed out for 45sec instead of dying
Practice=PRÁTICA

[GameOptions]
NativeCursor=CURSOR NATIVO
MouseLock=MOUSELOCK
PauseButton=BOTÃO DE PAUSA
AchievementPopups="POPUPS DE#CONQUISTA"
ProfileOptions=PERFIL

[R:Unlock]
GenericRace="@w% DESBLOQUEADO#@s%"
GenericSkin="@ASPECTO % DE w% DESBLOQUEADO#@s%"
Cheats="@wTRAPAÇAS DESBLOQUEADAS#@sVERIFIQUE AS OPÇÕES NO MENU PRINCIPAL!"

[Options]
CheatOptions=TRAPAÇAS
CharacterPrefOptions=PREFERÊNCIAS DE PERSONAGENS
ExperimentalOptions=OPÇÕES EXPERIMENTAIS
ProfileOptions=PERFIL

[VideoOptions]
WideScreen=WIDESCREEN
Bloom=BLOOM
Particles=PARTÍCULAS
DisplayOptions=OPÇÕES DE DISPLAY

[Bosses]
# "GUN GOD's" name isn't translated in the base game as of right now
GunGod="GUN#GOD"

[ExperimentalOptions]
KeyboardMode=MODO TECLADO
JoystickRegions=REGIÕES DE JOYSTICK
HideJoysticks=ESCONDER JOYSTICKS

[ResourcepackOptions]
ViewInstalled=VISUALIZAR INSTALADO
Browse=NAVEGAR DOWNLOADS
DirectDownload=DOWNLOAD DIRETO

[R:MainMenu]
AchievementHidden=SECRETO
Achievements=CONQUISTAS
Leaderboards=CLASSIFICAÇÕES

[R:CoopLobby]
Host=HOSPEDAR JOGO
RemoteAddress=ATUALIZAR JOGOS LOCAIS
RemotePort=PORTA REMOTA

[DataOptions]
OptionsReset=RESETAR OPÇÕES
ProgressReset=APAGAR PROGRESSO

[R:Tips]
ContinuedRun=bem-vindo de volta!

[R:MainMenu:Achievements]
Achievements=CONQUISTAS

[R:HUD]
PickUpAction=PEGAR

[R:GameOver]
Results=RESULTADOS