# Last updated on 18 January 2026 at 13:32 GMT+3

[ResourcepackBrowser]
LoadingList=LA LISTA ESTÁ CARGANDO...
InstallationSuccess="@g%#¡INSTALADO!##CLIC PARA CONTINUAR"
Installing=INSTALANDO %
InformationQuerying=SOLICITANDO INFO. DEL REPOSITORIO
# Max. 8 characters
ListRatingLabel=CALIFIC.
# Max. 8 characters
ListUpdateLabel=ACTUALZ.
# Installed resourcepack load order setting
LoadPriority=PRIORIDAD
SortMode=ORDEN
# Max. 8 characters
SortByUpdate=ACTUALZ.
# Max. 8 characters
SortByRating=CALIFIC.
NoPacksInstalled=NO HAY PACKS DE RECURSOS INSTALADOS
PackDisabled=DESACTIVADO
# Should be as short as possible
UpdatedLongAgo="HACE#MUCHO"
NewPackPromotion=NUEVO!
UpdatedJustNow=AHORA
UpdatedToday=HOY
UpdatedYesterday=AYER
UpdatedRecently=RECIENT.
UpdatedThisWeek="ESTA#SEM."
UpdatedDaysAgo="% D.#AGO"
ErrorMissingFiles=ARCHIVOS AUSENTES EN EL PACK
FullviewOpenGitHub=VER PÁG. GITHUB
ViewNoScreenshots=@dSIN CAPTURAS :(
FullviewPackInfo=INFO. PACK
FullviewCreationInfo=CREADO EN:
FullviewLastUpdate=ÚLTIMA ACTUALZ.:
FullviewInstallationDate=INSTALADO EN:
FullviewStars=ESTRELLAS:
ButtonDownload=DESCARGAR
ButtonDisable=DESACTIVAR
ButtonEnable=ACTIVAR

[ControlOptions]
GamepadOn=MANDO
GamepadStyle=ESTILO DE MANDO
AimAssist=ASIST. APUNTADO
AutoAim=APUNTADO AUTO.
# Allows swapping and using abilities by pressing volume buttons
VolumeControls=TECLAS DE VOLUMEN
# Split aim & fire into two separate control elements
SplitFireControls=APUNTAR Y DISPARAR
# Force player aim crosshair to be always visible
FixedSight=MIRILLA FIJA
TouchControlScale=ESCALA DE TAMAÑO
Remap=EDITAR CONTROLES
ResetTouchLayout=REINICIAR DISPOSICIÓN
SimpleTouchControls=SIMPLIFICAR
ButtonFire=DISPARAR
ButtonActive=ACTIVA
ButtonSwap=CAMBIAR
ButtonPick=RECOGER/USAR
ButtonChat=CHAT COOP.
ButtonUp=ARRIBA
ButtonDown=ABAJO
ButtonLeft=IZQUIERDA
ButtonRight=DERECHA
DebugOverlay=OVERLAY DE DEPURADO
ResetDefaults=AJUSTES PREDET.

[R:Intro]
LoadGameFailure=Error al cargar partida guardada.
# The message is padded with newlines only as a stylistic choice, but automatic wordwrapping is supported.
ProjectDisclaimerText="@w###ESTA ES UNA RECREACIÓN NO OFICIAL DEL JUEGO, HECHA POR FANS.#SU DESARROLLADOR NO ESTÁ AFILIADO A LOS AUTORES ORIGINALES - @yVLAMBEER@w.##ESTE ES UN JUEGO GRATIS Y DE CÓDIGO ABIERTO, DISTRIBUIDO EN ITCH.IO#Y SU CÓDIGO FUENTE ESTÁ DISPONIBLE EN GITHUB.##SI PAGASTE PARA ACCEDER A ESTE JUEGO O VES ANUNCIOS DURANTE EL JUEGO, SE RECOMIENDA#QUE DESINSTALES LA APLICACIÓN INMEDIATAMENTE."
ProjectDisclaimerTitle=AVISO
DisclaimerContinue=CLIC PARA CONTINUAR
LoadGameYes=SÍ
LoadGameNo=NO
LoadGameContinue=@s¿CONTINUAR ESTA PARTIDA GUARDADA?@w

[ResourcepackOptions]
# Delay before the user is able to proceed to resourcepack options
DisclaimerProceedWait=@sENTENDIDO (%)
DisclaimerProceed=@yENTENDIDO
DisclaimerText="LOS PACKS DE RECURSOS SON UNA CARACTERÍSTICA EXCLUSIVA DE#NUCLEAR THRONE MOBILE.##UN PACK DE RECURSOS ES UNA COLECCIÓN DE CONTENIDO HECHA POR EL USUARIO (TEXTURAS, SONIDOS, TEXTO) SOLO CON FINES DECORATIVOS, SIN BENEFICIOS DURANTE EL JUEGO.##EL NAVEGADOR DE PACKS DE RECURSOS, A PESAR DE RECIBIR MODERACIÓN,#PODRÍA CONTENER CONTENIDO CUESTIONABLE.##EL DESARROLLADOR NO ES RESPONSABLE DE NINGÚN CONTENIDO DAÑINO."
ResourcepackOptions=PACKS DE RECURSOS
ViewInstalled=VER INSTALADOS
Browse=BUSCAR Y DESCARGAR
DirectDownload=DESCARGA DIRECTA

[R:MainMenu]
AchievementHidden=OCULTO
Achievements=LOGROS
DiscordLink=¡ÚNETE A NUESTRO DISCORD!
RunHistory:daily=DIARIA
RunHistory:weekly=SEMANAL
RunHistoryScoreAVG=@dPUNT. PROMEDIO
Leaderboards=TABLAS DE CLASIF.
MultiplayerTBA="MULTIPLAYER WILL BE AVAILABLE#IN FUTURE UPDATES"
CustomModeTBA="CUSTOM MODE WILL BE AVAILABLE#IN FUTURE UPDATES"
RunHistory=HIST. DE PARTIDAS

[DataOptions]
OptionsResetDisclaimer="@wWARNING!!!##@sTHIS ACTION WILL COMPLETELY RESET#ALL OF YOUR PREFERENCES.###ARE YOU SURE?@w"
ProgressResetDisclaimer="@rWARNING!!!##@sTHIS ACTION WILL COMPLETELY RESET ALL OF YOUR#CHARACTERS, UNLOCKS, STATS, ACHIEVEMENTS AND#IT IS NOT UNDOABLE.###ARE YOU SURE?@w"
OptionsReset=RESTABLECER AJUSTES
ProgressReset=BORRAR PROGRESO

[CharacterPrefOptions]
CharacterLocked=BLOQUEADO
AutoTelekinesis=TELEQUINESIS AUTO.
AutoExplosions=EXPLOSIONES AUTO.
AutoSnare=CEPOS AUTO.
PopPopToggle=BLOQ. PIUM PIUM
DualWieldToggle=BLOQ. A DOS MANOS
UseWeaponWhenBeaming=USAR ARMAS Y RAYO
SwipeBombing=DESLIZAR PARA GOLPEAR
GambleToggle=BLOQ. APUESTA

[Weapons]
# Electric Guitar isn't translated in the basegame as of right now
128:Name=GUITARRA ELÉCTRICA
# Electric Guitar also uses the same description as the regular Guitar. NTM simply just adds a little sprinkle of detail to it
128:Text=fish puede rocanrolear

[ProfileOptions]
ColorHEX=EDITAR HEX
ColorSelectorNone=NINGUNO
ColorRed=ROJO
ColorGreen=VERDE
ColorBlue=AZUL
ID=ID
IDCopied=@g[COPIADO]
ProfileName=NOMBRE DEL PERFIL
ProfileNameInput=ENTER PROFILE NAME
ColorOptions=COLOR
ColorDefault=PREDET.
DataOptions=DATOS

[R:Stats]
# Important! Stat entries should be as short as possible.
# Total damage taken as Big Dog
Uniq13=DAÑO
# Skeleton's Blood gamble luck streak
Uniq14=RACHA SUERTE
# Amount of gas produced by Frog
Uniq15=GASES

[CheatOptions]
# Developer debug overlay
Console=CONSOLA
# Unlimited skill selection range
GrillerMode=MODO GRILLER
# Player gets timed out for 45sec instead of dying
Practice=PRÁCTICA

[Options]
Yes=YES
No=NO
CheatOptions=TRUCOS
CharacterPrefOptions=PREFERENCIAS DE PERSONAJES
ExperimentalOptions=AJUSTES EXPERIMENTALES
ProfileOptions=PERFIL

[R:Unlock]
GenericRace="@w% DESBLOQUEADO#@s%"
GenericSkin="@w% ASPECTO % DESBLOQUEADO#@s%"
Cheats="@wTRUCOS DESBLOQUEADOS#@s¡ENCUÉNTRALOS EN AJUSTES!"

[GameOptions]
NativeCursor=CURSOR NATIVO
MouseLock=BLOQ. RATÓN
PauseButton=BOTÓN DE PAUSA
AchievementPopups="LOGROS#EMERGENTES"
ProfileOptions=PERFIL

[VideoOptions]
WideScreen=PANT. PANORÁMICA
Bloom=BLOOM
Particles=PARTÍCULAS
DisplayOptions=AJUSTES DE PANTALLA

[ExperimentalOptions]
KeyboardMode=MODO TECLADO
JoystickRegions=REGIONES DE JOYST.
HideJoysticks=OCULTAR JOYSTICKS

[R:CoopLobby]
Host=JUGAR COMO ANFITRIÓN
RemoteAddress=BUSCAR JUEGOS LOCALES
RemotePort=PUERTO REMOTO

[Bosses]
# "GUN GOD's" name isn't translated in the base game as of right now
GunGod="GUN#GOD"

[R:Tips]
ContinuedRun=¡bienvenido de vuelta!

[AudioOptions]
SoundsVolume=VOLUMEN DE LOS EFECTOS

[R:HUD]
PickUpAction=RECOGER

[R:GameOver]
Results=RESULTADOS