# Last updated on 7 January 2026 at 04:12 GMT+3

[R:Intro]
LoadGameFailure=Error al cargar partida guardada.
# The message is padded with newlines only as a stylistic choice, but automatic wordwrapping is supported.
ProjectDisclaimerText="@w###ESTA ES UNA RECREACIÓN NO OFICIAL DEL JUEGO, HECHA POR FANÁTICOS.#SU DESARROLLADOR NO ESTÁ AFILIADO A LOS AUTORES ORIGINALES - @yVLAMBEER@w.##ESTE ES UN JUEGO GRATUITO Y DE CÓDIGO ABIERTO, ES DISTRIBUIDO EN ITCH.IO#Y SU CÓDIGO FUENTE ESTÁ TOTALMENTE DISPONIBLE EN GITHUB.##SI PAGASTE PARA ACCEDER A ESTE JUEGO, O VERÁS ANUNCIOS DURANTE EL JUEGO, ES RECOMENDADO#QUE DESINSTALES LA APLICACIÓN INMEDIATAMENTE."
ProjectDisclaimerTitle=AVISO
DisclaimerContinue=CLIC PARA CONTINUAR
LoadGameYes=SÍ
LoadGameNo=NO
LoadGameContinue=@sCONTINUAR ESTA PARTIDA GUARDADA?@w

[ControlOptions]
GamepadOn=MANDO
GamepadStyle=ESTILO DE MANDO
AimAssist=ASIST. APUNTADO
AutoAim=APUNTADO AUTO.
# Allows swapping and using abilities by pressing volume buttons
VolumeControls=TECLAS DE VOLUMEN
# Split aim & fire into two separate control elements
SplitFireControls=APUN. & DISP. DIV.
# Force player aim crosshair to be always visible
FixedSight=MIRILLA FIJA
TouchControlScale=ESCALA DE TAMAÑO
Remap=EDITAR CONTROLES
ResetTouchLayout=REINICIAR DISPOSICIÓN
SimpleTouchControls=SIMPLIFICAR
ButtonFire=DISPARAR
ButtonActive=ACTIVA
ButtonSwap=CAMBIAR
ButtonPick=RECOGER/USAR
ButtonChat=CHAT COOP.
ButtonUp=ARRIBA
ButtonDown=ABAJO
ButtonLeft=IZQUIERDA
ButtonRight=DERECHA
DebugOverlay=OVERLAY DE DEPURADO
ResetDefaults=AJUSTES PREDET.

[CharacterPrefOptions]
CharacterLocked=BLOQUEADO
AutoTelekinesis=TELEQUINESIS AUTO.
AutoExplosions=EXPLOSIONES AUTO.
AutoSnare=CEPOS AUTO.
PopPopToggle=BLOQ. PIUM PIUM
DualWieldToggle=BLOQ. A DOS MANOS
UseWeaponWhenBeaming=USAR ARMAS Y RAYO
SwipeBombing=DESLIZAR PARA GOLPEAR
GambleToggle=BLOQ. APUESTA

[Weapons]
# Electric Guitar isn't translated in the basegame as of right now
128:Name=GUITARRA ELÉCTRICA
# Electric Guitar also uses the same description as the regular Guitar. NTM simply just adds a little sprinkle of detail to it
128:Text=fish da volteretas chulas

[R:Stats]
# Important! Stat entries should be as short as possible.
# Total damage taken
Uniq13=HERIDO
# Blood gamble luck streak
Uniq14=R. SUERTE
# Amount of gas produced by the character
Uniq15=VOLUM. GAS

[ProfileOptions]
ColorHEX=EDITAR HEX.
ColorSelectorNone=NADA
ColorRed=ROJO
ColorGreen=VERDE
ColorBlue=AZUL
ID=ID
IDCopied=@g[COPIADO]
ProfileName=NOMBRE DE PERFIL
ColorOptions=COLOR
ColorDefault=PREDET.
DataOptions=DATOS

[CheatOptions]
# Developer debug overlay
Console=CONSOLA
# Unlimited skill selection range
GrillerMode=MODO GRILLER
# Player gets timed out for 45sec instead of dying
Practice=PRÁCTICA

[GameOptions]
NativeCursor=CURSOR NATIVO
MouseLock=BLOQ. RATÓN
PauseButton=BOTÓN DE PAUSA
AchievementPopups="LOGROS#EMERGENTES"
ProfileOptions=PERFIL

[R:Unlock]
GenericRace="@w% DESBLOQUEADO#@s%"
GenericSkin="@w% ASPECTO % DESBLOQUEADO#@s%"
Cheats="@wTRUCOS DESBLOQUEADOS#@sENCUÉNTRALOS EN AJUSTES!"

[Options]
CheatOptions=TRUCOS
CharacterPrefOptions=PREFERENCIAS DE PERSONAJES
ExperimentalOptions=AJUSTES EXPERIMENTALES
ProfileOptions=PERFIL

[VideoOptions]
WideScreen=PANORÁMICA
Bloom=BLOOM
Particles=PARTÍCULAS
DisplayOptions=AJUSTES DE PANTALLA

[Bosses]
# "GUN GOD's" name isn't translated in the base game as of right now
GunGod="GUN#GOD"

[ExperimentalOptions]
KeyboardMode=MODO TECLADO
JoystickRegions=REGIONES DE JOYST.
HideJoysticks=OCULTAR JOYSTICKS

[ResourcepackOptions]
ViewInstalled=VER INSTALADOS
Browse=BUSCAR Y DESCARGAR
DirectDownload=DESCARGA DIRECTA

[R:MainMenu]
AchievementHidden=OCULTO
Achievements=LOGROS
Leaderboards=TABLAS DE CLASIF.

[R:CoopLobby]
Host=JUGAR COMO ANFITRIÓN
RemoteAddress=BUSCAR JUEGOS LOCALES
RemotePort=PUERTO REMOTO

[DataOptions]
OptionsReset=RESTABLECER AJUSTES
ProgressReset=BORRAR PROGRESO

[R:Tips]
ContinuedRun=bienvenido de vuelta!

[R:MainMenu:Achievements]
Achievements=LOGROS

[R:HUD]
PickUpAction=RECOGER

[R:GameOver]
Results=RESULTADOS
