# Last updated on 18 January 2026 at 13:32 GMT+3

[R:Intro]
LoadGameFailure=Не удалось загрузить сохранённую игру.
# The message is padded with newlines only as a stylistic choice, but automatic wordwrapping is supported.
ProjectDisclaimerText="@w###ДАННЫЙ ПРОЕКТ - НЕОФИЦИАЛЬНОЕ#ФАНАТСКОЕ ВОССОЗДАНИЕ ИГРЫ, РАЗРАБОТЧИК КОТОРОГО#НЕ ИМЕЕТ НИКАКОГО ОТНОШЕНИЯ К @yVLAMBEER@w.##ЭТА ВЕРСИЯ ИГРЫ#РАСПРОСТРАНЯЕТСЯ БЕСПЛАТНО НА ITCH.IO,#А ТАК ЖЕ ИМЕЕТ ОТКРЫТЫЙ ИСХОДНЫЙ КОД НА GITHUB.##ЕСЛИ ВЫ ЗАПЛАТИЛИ ЗА ДОСТУП К ЭТОЙ ИГРЕ#ИЛИ УВИДИТЕ ВО ВРЕМЯ ИГРЫ РЕКЛАМУ,#РЕКОМЕНДУЕТСЯ УДАЛИТЬ ПРИЛОЖЕНИЕ."
ProjectDisclaimerTitle=ДИСКЛЕЙМЕР
DisclaimerContinue=НАЖМИТЕ, ЧТОБЫ ПРОДОЛЖИТЬ
LoadGameYes=ДА
LoadGameNo=НЕТ
LoadGameContinue=@sХОТИТЕ ПРОДОЛЖИТЬ СОХРАНЁННУЮ ИГРУ?
FilesystemAccess=Игра требует доступа к чтению и записи файлов для настройки и сохранения вашего прогресса.\nВы можете отозвать это разрешение в Системных настройках, если у вас возникнут проблемы с игровыми данными.
FilesystemAccessV3Update=Обнаружена предыдущая установка игры. В связи с недавними внутренними миграциями API, вы должны предоставить приложению доступ к файловой системе вашего устройства, чтобы сохранить прогресс весь ваших сохранений.\n\nЭто можно сделать только сейчас и отозвать разрешение сразу же после, если вам не требуется доступ к редактированию сохранений.

[ResourcepackBrowser]
LoadingList=СПИСОК ЗАГРУЖАЕТСЯ...
InstallationSuccess="@g%#УСПЕШНО УСТАНОВЛЕНО!##НАЖМИТЕ, ЧТОБЫ ПРОДОЛЖИТЬ"
Installing=УСТАНОВКА %
InformationQuerying="ИДЁТ ЗАПРОС ИНФОРМАЦИИ#О РЕПОЗИТОРИИ..."
# Max. 8 characters
ListRatingLabel=ОЦЕНКА
# Max. 8 characters
ListUpdateLabel=ОБНОВЛЁН
# Installed resourcepack load order setting
LoadPriority=ПРИОРИТЕТ
SortMode=ПОРЯДОК
# Max. 8 characters
SortByUpdate=ОБНОВЛЕНИЯ
# Max. 8 characters
SortByRating=ОЦЕНКА
NoPacksInstalled=УСТАНОВЛЕННЫЕ РЕСУРСПАКИ ОТСУТСТВУЮТ.
PackDisabled=ОТКЛЮЧЕНО
# Should be as short as possible
UpdatedLongAgo="ОЧЕНЬ#ДАВНО"
NewPackPromotion=НОВОЕ!
UpdatedJustNow="ТОЛЬКО#ЧТО"
UpdatedToday=СЕГОДНЯ
UpdatedYesterday=ВЧЕРА
UpdatedRecently=НЕДАВНО
UpdatedThisWeek="НА ЭТОЙ#НЕДЕЛЕ"
UpdatedDaysAgo="% ДН.#НАЗАД"
ErrorMissingFiles=ОТСУТСТВУЮТ ФАЙЛЫ РЕСУРСПАКА
FullviewOpenGitHub=СТРАНИЦА НА GITHUB
ViewNoScreenshots=@dНЕТ СКРИНШОТОВ :(
FullviewPackInfo=ИНФОРМАЦИЯ
FullviewCreationInfo=ДАТА СОЗДАНИЯ:
FullviewLastUpdate=ДАТА ОБНОВЛЕНИЯ:
FullviewInstallationDate=ДАТА УСТАНОВКИ:
FullviewStars=ЗВЁЗДЫ:
ButtonDownload=СКАЧАТЬ
ButtonDisable=ОТКЛЮЧИТЬ
ButtonEnable=ВКЛЮЧИТЬ

[ControlOptions]
GamepadOn=КОНТРОЛЛЕР
GamepadStyle=СИТИЛЬ КНОПОК
AimAssist=ДОНАВЕДЕНИЕ
AutoAim="ПОЛНОЕ#АВТОНАВЕДЕНИЕ"
# Allows swapping and using abilities by pressing volume buttons
VolumeControls="УПРАВЛЕНИЕ#ГРОМКОСТЬЮ"
# Split aim & fire into two separate control elements
SplitFireControls="РАЗДЕЛЬНАЯ#СТРЕЛЬБА"
# Force player aim crosshair to be always visible
FixedSight="ФИКСИРОВАТЬ#ПЕРЕКРЕСТЬЕ"
TouchControlScale=МАСШТАБ
Remap=ИЗМЕНИТЬ УПРАВЛЕНИЕ
ResetTouchLayout=СБРОСИТЬ ПОЛОЖЕНИЕ
SimpleTouchControls=УПРОЩЁННЫЙ ВИД
ButtonFire=СТРЕЛЬБА
ButtonActive="АКТИВНАЯ#СПОСОБНОСТЬ"
ButtonSwap=СМЕНИТЬ ОРУЖИЕ
ButtonPick=ПОДОБРАТЬ
ButtonChat=ОТКРЫТЬ ЧАТ
ButtonUp=ВВЕРХ
ButtonDown=ВНИЗ
ButtonLeft=ВЛЕВО
ButtonRight=ВПРАВО
DebugOverlay=КНОПКА ОТЛАДКИ
ResetDefaults=СБРОС ПО УМОЛЧАНИЮ

[ResourcepackOptions]
# Delay before the user is able to proceed to resourcepack options
DisclaimerProceedWait=@sПРОДОЛЖИТЬ (%)
DisclaimerProceed=@yПРОДОЛЖИТЬ
DisclaimerText="RESOURCEPACKS ARE AN EXCLUSIVE FEATURE OF#NUCLEAR THRONE MOBILE.##A RESOURCEPACK IS A USER-CREATED ASSET COLLECTION (TEXTURES, SOUNDS, TEXT) FOR DECORATIVE PURPOSES ONLY, WITH NO GAMEPLAY BENEFITS.##RESOURCEPACK BROWSER, DESPITE BEING MODERATED,#MAY STILL CONTAIN QUESTIONABLE CONTENT.##THE DEVELOPER IS NOT LIABLE FOR ANY HARMFUL MATERIAL."
ResourcepackOptions=РЕСУРСПАКИ
ViewInstalled=ПОСМОТРЕТЬ УСТАНОВЛЕННОЕ
Browse=БРАУЗЕР РЕСУРСПАКОВ
DirectDownload=ПРЯМОЕ СКАЧИВАНИЕ

[DataOptions]
OptionsResetDisclaimer="@wВНИМАНИЕ!##@sДАННОЕ ДЕЙСТВИЕ БЕЗВОЗВРАТНО СБРОСИТ#ВСЕ ВАШИ НАСТРОЙКИ.###ВЫ ТОЧНО ХОТИТЕ ЭТО СДЕЛАТЬ?@w"
ProgressResetDisclaimer="@rОСТОРОЖНО!!!##@sДАННОЕ ДЕЙСТВИЕ ПОЛНОСТЬЮ СБРОСИТ ВЕСЬ ВАШ ПРОГРЕСС:#ВСЕ ВАШИ ПЕРСОНАЖИ, ДОСТИЖЕНИЯ И СТАТИСТИКА#БУДУТ БЕЗВОЗВРАТНО АННУЛИРОВАНЫ.###ВЫ ТОЧНО ХОТИТЕ ЭТО СДЕЛАТЬ?@w"
OptionsReset=СБРОСИТЬ НАСТРОЙКИ
ProgressReset=СТЕРЕТЬ ПРОГРЕСС

[Options]
Yes=ДА
No=НЕТ
CheatOptions=ЧИТЫ
CharacterPrefOptions=ОПЦИИ ПЕРСОНАЖЕЙ
ExperimentalOptions=ЭКСПЕРИМЕНТАЛЬНЫЕ НАСТРОЙКИ
ProfileOptions=ПРОФИЛЬ
CoopOptions=СОВМ. ИГРА
KeyRemappingOptions=ПЕРЕНАЗНАЧ. КЛАВИШ
TouchRemappingOptions=ИЗМЕНИТЬ УПРАВЛЕНИЕ
DataOptions=ДАННЫЕ
ColorOptions=ВЫБОР ЦВЕТА
DisplayOptions=ДИСПЛЕЙ
ResourcepackOptions=РЕСУРСПАКИ

[R:MainMenu]
AchievementHidden=Скрыто
Achievements=Достижения
DiscordLink=DISCORD СЕРВЕР
RunHistory:daily=ЕЖЕДНЕВНЫЙ
RunHistory:weekly=ЕЖЕНЕДЕЛЬНЫЙ
RunHistoryScoreAVG=@dСРЕДНИЙ СЧЁТ
Leaderboards=Рекорды
MultiplayerTBA="MULTIPLAYER WILL BE AVAILABLE#IN FUTURE UPDATES"
CustomModeTBA="CUSTOM MODE WILL BE AVAILABLE#IN FUTURE UPDATES"
RunHistory=История забегов

[CharacterPrefOptions]
CharacterLocked=ЗАКРЫТО
AutoTelekinesis=АВТО ТЕЛЕКИНЕЗ
AutoExplosions=АВТО ВЗРЫВы
AutoSnare=АВТО СИЛКИ
PopPopToggle=АВТО БАХ-БАХА
DualWieldToggle=ПЕРЕКЛ. СТРЕЛЬБЫ
UseWeaponWhenBeaming=СТРЕЛЬБА ПРИ ЛУЧЕ
SwipeBombing=БОМБАРДИРОВКА ЖЕСТОМ
GambleToggle=АВТО РУЛЕТКА

[Weapons]
# Electric Guitar isn't translated in the basegame as of right now
128:Name=ЭЛЕКТРОГИТАРА
# Electric Guitar also uses the same description as the regular Guitar. NTM simply just adds a little sprinkle of detail to it
128:Text=РЫБ УМЕЕТ КАТАТЬСЯ И ЗАЖИГАТЬ

[ProfileOptions]
ColorHEX=ИЗМЕНИТЬ
ColorSelectorNone=НЕТ
ColorRed=КРАСНЫЙ
ColorGreen=ЗЕЛЕНЫЙ
ColorBlue=СИНИЙ
ID=ID
IDCopied=@g[СКОПИРОВАНО]
ProfileName=НАЗВАНИЕ
ProfileNameInput=ВВЕДИТЕ НАЗВАНИЕ ПОФИЛЯ
ColorOptions=ЦВЕТ
ColorDefault=СТАНДАРТ
DataOptions=ДАННЫЕ

[R:Stats]
# Important! Stat entries should be as short as possible.
# Total damage taken as Big Dog
Uniq13=ПОВРЕЖДЕНИЙ
# Skeleton's Blood gamble luck streak
Uniq14=УДАЧА ПОДРЯД
# Amount of gas produced by Frog
Uniq15=КБ.М. ГАЗА

[GameOptions]
NativeCursor="АППАРАТНЫЙ#КУРСОР"
MouseLock="УДЕРЖАНИЕ#МЫШИ В ОКНЕ"
PauseButton=КНОПКА ПАУЗЫ
AchievementPopups="ПОКАЗЫВАТЬ#ДОСТИЖЕНИЯ"
ProfileOptions=ПРОФИЛЬ
DynamicCamera=АКТИВНАЯ КАМЕРА
BossIntros=ЗАСТАВКИ БОССОВ

[CheatOptions]
# Developer debug overlay
Console=КОНСОЛЬ
# Unlimited skill selection range
GrillerMode=ВСЕ МУТАЦИИ
# Player gets timed out for 45sec instead of dying
Practice=ПРАКТИКА

[R:Unlock]
GenericRace="@w% ОТКРЫТ#@s%"
GenericSkin="@w% ОБЛИК % ОТКРЫТ#@s%"
Cheats="@wЧИТЫ РАЗБЛОКИРОВАНЫ@s#ПРОВЕРЬТЕ НАСТРОЙКИ В ГЛАВНОМ МЕНЮ!"

[R:CoopLobby]
Host=СОЗДАТЬ ИГРУ
RemoteAddress=АДРЕСС
RemotePort=ПОРТ
Join=ПРИСОЕДИНИТЬСЯ
RefreshLocal=ОБНОВИТЬ ЛОКАЛЬНЫЙ СПИСОК

[VideoOptions]
WideScreen=ШИРОКИЙ ЭКРАН
Bloom=СВЕЧЕНИЕ
Particles=ЧАСТИЦЫ
DisplayOptions=НАСТРОЙКИ ДИСПЛЕЯ

[ExperimentalOptions]
KeyboardMode=КЛАВИАТУРНЫЙ РЕЖИМ
JoystickRegions=РЕГИОНЫ СТИКОВ
HideJoysticks=СКРЫВАТЬ СТИКИ

[Bosses]
# "GUN GOD's" name isn't translated in the base game as of right now
GunGod="БОГ#ПУШЕК"

[R:Tips]
ContinuedRun=Добро пожаловать обратно!

[AudioOptions]
SoundsVolume=ЗВУКИ ЭФФЕКТОВ

[R:HUD]
PickUpAction=ПОДОБРАТЬ

[R:GameOver]
Results=РЕЗУЛЬТАТЫ