# Last updated on 8 February 2026 at 18:43 GMT+3

[ResourcepackBrowser]
LoadingList=正在加载资源包列表...
InstallationSuccess="@g%#安装成功!##点击任何地方以继续"
Installing=安装中 %
InformationQuerying=正在查询信息
# Max. 8 characters
ListRatingLabel=评分
# Max. 8 characters
ListUpdateLabel=下载量
# Installed resourcepack load order setting
LoadPriority=加载优先级
SortMode=排序
# Max. 8 characters
SortByUpdate=按下载量
# Max. 8 characters
SortByRating=按评分
NoPacksInstalled=当前未安装任何资源包.
PackDisabled=卸载
# Should be as short as possible
UpdatedLongAgo=很久之前
NewPackPromotion=新的!
UpdatedJustNow=刚刚
UpdatedToday=今天
UpdatedYesterday=昨天
UpdatedRecently=最近
UpdatedThisWeek=本周
UpdatedDaysAgo="% D.#AGO"
ErrorMissingFiles=资源包文件丢失
FullviewOpenGitHub=详见GITHUB界面
ViewNoScreenshots=@d没有相关截图信息 :(
FullviewPackInfo=资源包信息
FullviewCreationInfo=创建时间:
FullviewLastUpdate=上次更新:
FullviewInstallationDate=安装时间:
FullviewStars=星级评分:
ButtonDownload=下载
ButtonDisable=取消载入
ButtonEnable=载入

[ControlOptions]
GamepadOn=手柄
GamepadStyle=切换手柄风格
AimAssist=辅助瞄准
AutoAim=自动瞄准
# Allows swapping and using abilities by pressing volume buttons
VolumeControls=音量键控制技能
# Split aim & fire into two separate control elements
SplitFireControls=分离瞄准&开火
# Force player aim crosshair to be always visible
FixedSight=固定准心
TouchControlScale=摇杆大小
Remap=键位调整
ResetTouchLayout=重置键位
SimpleTouchControls=简洁按键
ButtonFire=开火
ButtonActive=技能
ButtonSwap=切换
ButtonPick=拾取/使用
ButtonChat=多人聊天
ButtonUp=向上走
ButtonDown=向下走
ButtonLeft=向左走
ButtonRight=向右走
DebugOverlay=调试界面
ResetDefaults=默认预设

[R:Intro]
LoadGameFailure=加载失败.
# The message is padded with newlines only as a stylistic choice, but automatic wordwrapping is supported.
ProjectDisclaimerText="@w###这是一个非官方的粉丝移植手游.#移植者与原作者无任何关系, 原作者 - @yVLAMBEER@w.##这是一款在ITCH.IO上免费发布的游戏#以及它在GITHUB上是完全开源的.##如果你通过付费获取了这款游戏, 或者在游戏中看见了广告植入, 建议你#立刻, 马上, 将它卸载."
ProjectDisclaimerExclamationsLeft=!!!
ProjectDisclaimerExclamationsRight=!!!
ProjectDisclaimerTitle=免责声明
DisclaimerContinue=点击以继续
LoadGameYes=是的
LoadGameNo=不了
LoadGameContinue=@s要从上次的游戏进度继续吗?@w

[ResourcepackOptions]
# Delay before the user is able to proceed to resourcepack options
DisclaimerProceedWait=@s继续(%)
DisclaimerProceed=@y继续
DisclaimerText="资源包是废土之王手游#独有的功能.##资源包是用户创建的资源集合(包含游戏纹理, 音效和文本), 仅用于装饰目的, 没有游戏性上的扩充.##这些资源包虽经必应审核,#但仍可能包含一些不当内容.##开发者对此不承担任何法律责任."
ResourcepackOptions=资源包
ViewInstalled=查看已安装资源包
Browse=浏览并下载资源包
DirectDownload=直接下载资源包

[DataOptions]
OptionsResetDisclaimer="@wWARNING!!!##@sTHIS ACTION WILL COMPLETELY RESET#ALL OF YOUR PREFERENCES.###ARE YOU SURE?@w"
ProgressResetDisclaimer="@rWARNING!!!##@sTHIS ACTION WILL COMPLETELY RESET ALL OF YOUR#CHARACTERS, UNLOCKS, STATS, ACHIEVEMENTS AND#IT IS NOT UNDOABLE.###ARE YOU SURE?@w"
OptionsReset=重置所有设置
ProgressReset=清除游戏数据

[R:MainMenu]
AchievementHidden=隐藏
Achievements=成就
DiscordLink=加入我们的DISCORD频道!
RunHistory:daily=每日挑战记录
RunHistory:weekly=每周挑战记录
RunHistoryScoreAVG=@d平均记录
Leaderboards=排行榜
MultiplayerTBA="MULTIPLAYER WILL BE AVAILABLE#IN FUTURE UPDATES"
CustomModeTBA="CUSTOM MODE WILL BE AVAILABLE#IN FUTURE UPDATES"
RunHistory=挑战记录

[Tutorial]
Touch:1=WALK USING @wMOVEMENT STICK
Touch:2=PICK UP NEW WEAPON USING THE @wINTERACT BUTTON
Touch:3="AIM USING THE @wATTACK JOYSTICK@s#TOUCHING THEN RELEASING WILL FIRE"
Touch:4="SWAP WEAPONS USING THE @wSWAP BUTTON#TRY IT A FEW TIMES!"
Touch:5="@wABILITY BUTTON@s USES YOUR SPECIAL SKILL#@wGIVE IT A GO!"

[Weapons]
# Electric Guitar isn't translated in the basegame as of right now
128:Name=电吉他
# Electric Guitar also uses the same description as the regular Guitar. NTM simply just adds a little sprinkle of detail to it
128:Text=鱼可以翻滚, 也可以摇滚

[Options]
Yes=YES
No=NO
CheatOptions=作弊选项
# Touch controls
TouchRemappingOptions=REMAPPING
# Keyboard/gamepad controls
KeyRemappingOptions=REMAPPING
CharacterPrefOptions=角色技能偏好
ExperimentalOptions=实验性功能
ProfileOptions=个人资料

[CharacterPrefOptions]
CharacterLocked=已锁定
AutoTelekinesis=自动使用念动力
AutoExplosions=自动产生尸爆
AutoSnare=开火时自动发射种子
PopPopToggle=一键切换双倍火力
DualWieldToggle=一键切换双持武器
UseWeaponWhenBeaming=开火的同时发射光束
SwipeBombing=滑动屏幕产生爆炸
GambleToggle=一键切换赌血射击

[R:Stats]
# Important! Stat entries should be as short as possible.
# Total damage taken as Big Dog
Uniq13=累计所受伤害
# Skeleton's Blood gamble luck streak
Uniq14=赌血成功次数
# Amount of gas produced by Frog
Uniq15=毒气产生量

[ProfileOptions]
ColorHEX=编辑RGB值
ColorSelectorNone=默认颜色
ColorRed=R
ColorGreen=G
ColorBlue=B
ID=玩家ID
IDCopied=@g[已复制ID]
ProfileName=玩家名称
ProfileNameInput=输入玩家名称
ColorOptions=颜色设置
ColorDefault=默认颜色
DataOptions=游戏数据管理

[CheatOptions]
# Developer debug overlay
Console=启用控制台
# Unlimited skill selection range
GrillerMode=启用变异自选
# Player gets timed out for 45sec instead of dying
Practice=启用种子

[GameOptions]
NativeCursor=系统光标
MouseLock=鼠标锁定
PauseButton=暂停键
AchievementPopups="成就#弹窗"
ProfileOptions=个人资料

[PauseMenu]
RunSavingTip="YOU CAN SAVE AND CONTINUE THIS RUN LATER#IF YOU EXIT WITHOUT QUITTING TO MAIN MENU"

[R:Unlock]
GenericRace="@w% 已解锁#@s%"
GenericSkin="@w% %-皮肤已解锁#@s%"
Cheats="@w作弊选项已解锁#@s去看看主菜单设置!"

[MonthNameShort]
1=JAN
2=FEB
3=MAR
4=APR
5=MAY
6=JUN
7=JUL
8=AUG
9=SEP
10=OCT
11=NOV
12=DEC

[Bosses]
# "GUN GOD's" name isn't translated in the base game as of right now
GunGod=枪神

[VideoOptions]
WideScreen=宽屏显示
Bloom=泛光特效
Particles=粒子
DisplayOptions=显示设置

[ExperimentalOptions]
KeyboardMode=键盘模式
JoystickRegions=摇杆区域
HideJoysticks=隐藏摇杆

[R:CoopLobby]
Host=创建房间
RemoteAddress=刷新本地游戏
RemotePort=远程端口

[R:Tips]
ContinuedRun=欢迎回来!

[AudioOptions]
SoundsVolume=音效音量

[R:MainMenu:Achievements]
Achievements=成就

[R:HUD]
PickUpAction=拾取

[R:GameOver]
Results=结算