# Last updated on 8 January 2026 at 05:16 GMT+3

[ResourcepackBrowser]
LoadingList=THE LIST IS LOADING...
InstallationSuccess="@g%#INSTALLED SUCCESSFULLY!##CLICK ANYHWHERE TO CONTINUE"
Installing=INSTALLING %
InformationQuerying=QUERYING REPO INFO
# Max. 8 characters
ListRatingLabel=RATING
# Max. 8 characters
ListUpdateLabel=UPDATED
# Installed resourcepack load order setting
LoadPriority=LOAD PRIORITY
SortMode=SORT
# Max. 8 characters
SortByUpdate=UPDATED
# Max. 8 characters
SortByRating=RATING
NoPacksInstalled=NO RESOURCEPACKS ARE CURRENTLY INSTALLED.
PackDisabled=DISABLED
# Should be as short as possible
UpdatedLongAgo="LONG#AGO"
NewPackPromotion=NEW!
UpdatedJustNow=JUST NOW
UpdatedToday=TODAY
UpdatedYesterday=YESTERDAY
UpdatedRecently=RECENTLY
UpdatedThisWeek="THIS#WEEK"
ErrorMissingFiles=MISSING RESOURCEPACK FILES
FullviewOpenGitHub=SEE GITHUB PAGE
ViewNoScreenshots=@dNO SCREENSHOTS :(
FullviewPackInfo=PACK INFO
FullviewCreationInfo=CREATED ON:
FullviewLastUpdate=LAST UPDATED:
FullviewInstallationDate=INSTALLED ON:
FullviewStars=STARS:
ButtonDownload=DOWNLOAD
ButtonDisable=DISABLE
ButtonEnable=ENABLE


[ResourcepackOptions]
DisclaimerText="RESOURCEPACKS ARE AN EXCLUSIVE FEATURE OF#NUCLEAR THRONE MOBILE.##A RESOURCEPACK IS A USER-CREATED ASSET COLLECTION (TEXTURES, SOUNDS, TEXT) FOR DECORATIVE PURPOSES ONLY, WITH NO GAMEPLAY BENEFITS.##RESOURCEPACK BROWSER, DESPITE BING MODERATED,#MAY STILL CONTAIN QUESTIONABLE CONTENT.##THE DEVELOPER IS NOT LIABLE FOR ANY HARMFUL MATERIAL."
# Delay before the user is able to proceed to resourcepack options
DisclaimerProceedWait=@sPROCEED (%)
DisclaimerProceed=@yPROCEED
ResourcepackOptions=RESOURCEPACKS
ViewInstalled=查看已安装资源包
Browse=浏览并下载资源包
DirectDownload=直接下载资源包

[ControlOptions]
GamepadOn=手柄
GamepadStyle=切换手柄风格
AimAssist=辅助瞄准
AutoAim=自动瞄准
# Allows swapping and using abilities by pressing volume buttons
VolumeControls=音量键控制技能
# Split aim & fire into two separate control elements
SplitFireControls=分离瞄准&开火
# Force player aim crosshair to be always visible
FixedSight=固定准心
TouchControlScale=摇杆大小
Remap=键位调整
ResetTouchLayout=重置键位
SimpleTouchControls=简洁按键
ButtonFire=开火
ButtonActive=技能
ButtonSwap=切换
ButtonPick=拾取/使用
ButtonChat=多人聊天
ButtonUp=向上走
ButtonDown=向下走
ButtonLeft=向左走
ButtonRight=向右走
DebugOverlay=调试界面
ResetDefaults=默认预设

[R:Intro]
LoadGameFailure=加载失败.
# The message is padded with newlines only as a stylistic choice, but automatic wordwrapping is supported.
ProjectDisclaimerText="@w###这是一个非官方的粉丝移植手游.#移植者与原作者无任何关系, 原作者 - @yVLAMBEER@w.##这是一款在ITCH.IO上免费发布的游戏#以及它在GITHUB上是完全开源的.##如果你通过付费获取了这款游戏, 或者在游戏中看见了广告植入, 建议你#立刻, 马上, 将它卸载."
ProjectDisclaimerTitle=免责声明
DisclaimerContinue=点击以继续
LoadGameYes=是的
LoadGameNo=不了
LoadGameContinue=@s要从上次的游戏进度继续吗?@w

[Weapons]
# Electric Guitar isn't translated in the basegame as of right now
128:Name=电吉他
# Electric Guitar also uses the same description as the regular Guitar. NTM simply just adds a little sprinkle of detail to it
128:Text=鱼可以翻滚, 也可以摇滚

[ProfileOptions]
ColorHEX=编辑RGB值
ColorSelectorNone=默认颜色
ColorRed=R
ColorGreen=G
ColorBlue=B
ID=玩家ID
IDCopied=@g[已复制ID]
ProfileName=玩家名称
ProfileNameInput=ENTER PROFILE NAME
ColorOptions=颜色设置
ColorDefault=默认颜色
DataOptions=游戏数据管理

[CharacterPrefOptions]
CharacterLocked=已锁定
AutoTelekinesis=自动使用念动力
AutoExplosions=自动产生尸爆
AutoSnare=开火时自动发射种子
PopPopToggle=一键切换双倍火力
DualWieldToggle=一键切换双持武器
UseWeaponWhenBeaming=开火的同时发射光束
SwipeBombing=滑动屏幕产生爆炸
GambleToggle=一键切换赌血射击

[R:Stats]
# Important! Stat entries should be as short as possible.
# Total damage taken
Uniq13=累计所受伤害
# Blood gamble luck streak
Uniq14=赌血成功次数
# Amount of gas produced by the character
Uniq15=毒气产生量

[R:MainMenu]
AchievementHidden=隐藏
Achievements=成就
DiscordLink=JOIN OUR DISCORD!
RunHistory:daily=DAILY
RunHistory:weekly=WEEKLY
RunHistoryScoreAVG=@dAVERAGE SCORE
Leaderboards=排行榜
RunHistory=RUN HISTORY

[CheatOptions]
# Developer debug overlay
Console=启用控制台
# Unlimited skill selection range
GrillerMode=启用变异自选
# Player gets timed out for 45sec instead of dying
Practice=启用种子

[GameOptions]
NativeCursor=系统光标
MouseLock=鼠标锁定
PauseButton=暂停键
AchievementPopups="成就#弹窗"
ProfileOptions=个人资料

[Options]
CheatOptions=作弊选项
CharacterPrefOptions=角色技能偏好
ExperimentalOptions=实验性功能
ProfileOptions=个人资料

[R:Unlock]
GenericRace="@w% 已解锁#@s%"
GenericSkin="@w% %-皮肤已解锁#@s%"
Cheats="@w作弊选项已解锁#@s去看看主菜单设置!"

[Bosses]
# "GUN GOD's" name isn't translated in the base game as of right now
GunGod=枪神

[VideoOptions]
WideScreen=宽屏显示
Bloom=泛光特效
Particles=粒子
DisplayOptions=显示设置

[ExperimentalOptions]
KeyboardMode=键盘模式
JoystickRegions=摇杆区域
HideJoysticks=隐藏摇杆

[R:CoopLobby]
Host=创建房间
RemoteAddress=刷新本地游戏
RemotePort=远程端口

[DataOptions]
OptionsReset=重置所有设置
ProgressReset=清除游戏数据

[AudioOptions]
SoundsVolume=EFFECTS VOLUME

[R:Tips]
ContinuedRun=欢迎回来!

[R:MainMenu:Achievements]
Achievements=成就

[R:HUD]
PickUpAction=拾取

[R:GameOver]
Results=结算