# Last updated on 7 January 2026 at 04:12 GMT+3

[R:Intro]
LoadGameFailure=載入失敗.
# The message is padded with newlines only as a stylistic choice, but automatic wordwrapping is supported.
ProjectDisclaimerText="@w###這是粉絲自製的非官方移植遊戲.#移植者與原作者毫無關聯, 原作者 - @yVLAMBEER@w.##此遊戲在ITCH.IO上是免費的#並且在GITHUB上是完全開源的.##如果您是付費下載此遊戲, 或在遊戲內看到了廣告, 請您#立即解除安裝."
ProjectDisclaimerTitle=免責聲明
DisclaimerContinue=點擊以繼續
LoadGameYes=是的
LoadGameNo=不了
LoadGameContinue=@s要繼續上一局的遊戲進程嗎?@w

[ControlOptions]
GamepadOn=手柄
GamepadStyle=切換手柄風格
AimAssist=輔助瞄準
AutoAim=自動瞄準
# Allows swapping and using abilities by pressing volume buttons
VolumeControls=音量鍵控制技能
# Split aim & fire into two separate control elements
SplitFireControls=分離瞄準&開火
# Force player aim crosshair to be always visible
FixedSight=固定准心
TouchControlScale=搖杆大小
Remap=鍵位調整
ResetTouchLayout=重置鍵位
SimpleTouchControls=按鍵簡潔化
ButtonFire=開火
ButtonActive=技能
ButtonSwap=切換
ButtonPick=拾起/使用
ButtonChat=多人聊天
ButtonUp=向上走
ButtonDown=向下走
ButtonLeft=向左走
ButtonRight=向右走
DebugOverlay=調試介面
ResetDefaults=預設

[CharacterPrefOptions]
CharacterLocked=已鎖定
AutoTelekinesis=自動使用念動力
AutoExplosions=自動產生屍爆
AutoSnare=開火時發射種子
PopPopToggle=一鍵切換雙倍火力
DualWieldToggle=一鍵切換雙持武器
UseWeaponWhenBeaming=開火同時發射光束
SwipeBombing=滑動產生爆炸
GambleToggle=一鍵切換賭血射擊

[Weapons]
# Electric Guitar isn't translated in the basegame as of right now
128:Name=電吉他
# Electric Guitar also uses the same description as the regular Guitar. NTM simply just adds a little sprinkle of detail to it
128:Text=魚會翻滾, 也會搖滾

[R:Stats]
# Important! Stat entries should be as short as possible.
# Total damage taken
Uniq13=累積受擊次數
# Blood gamble luck streak
Uniq14=賭血成功次數
# Amount of gas produced by the character
Uniq15=毒氣產生量

[ProfileOptions]
ColorHEX=編輯RGB值
ColorSelectorNone=默認顏色
ColorRed=R
ColorGreen=G
ColorBlue=B
ID=玩家ID
IDCopied=@g[已複製ID]
ProfileName=玩家名稱
ColorOptions=顏色設定
ColorDefault=默認顏色
DataOptions=數據管理

[CheatOptions]
# Developer debug overlay
Console=調取控制台
# Unlimited skill selection range
GrillerMode=啟用變異自選
# Player gets timed out for 45sec instead of dying
Practice=啟用種子

[GameOptions]
NativeCursor=系統指針
MouseLock=鼠標鎖定
PauseButton=暫停鍵
AchievementPopups="成就#視窗"
ProfileOptions=個人資料

[R:Unlock]
GenericRace="@w% 已解鎖#@s%"
GenericSkin="@w% %-皮膚已解鎖#@s%"
Cheats="@w作弊選項已解鎖#@s請檢查您的主選單!"

[Options]
CheatOptions=作弊選項
CharacterPrefOptions=角色技能偏好
ExperimentalOptions=實驗性功能
ProfileOptions=個人資料

[VideoOptions]
WideScreen=寬屏顯示
Bloom=泛光特效
Particles=粒子
DisplayOptions=顯示設定

[Bosses]
# "GUN GOD's" name isn't translated in the base game as of right now
GunGod="槍神"

[ExperimentalOptions]
KeyboardMode=鍵盤模式
JoystickRegions=搖杆區域
HideJoysticks=隱藏搖杆

[ResourcepackOptions]
ViewInstalled=檢視已安裝資源包
Browse=預覽&下載資源包
DirectDownload=直接下載資源包

[R:MainMenu]
AchievementHidden=隱藏
Achievements=成就
Leaderboards=排行榜

[R:CoopLobby]
Host=創建房間
RemoteAddress=刷新本地遊戲
RemotePort=遠程端口

[DataOptions]
OptionsReset=重置所有設定
ProgressReset=清除遊戲數據

[R:Tips]
ContinuedRun=歡迎回來!

[R:MainMenu:Achievements]
Achievements=成就

[R:HUD]
PickUpAction=拾起

[R:GameOver]
Results=結算
