# Last updated on 17 January 2026 at 23:48 GMT+3

[ResourcepackBrowser]
LoadingList=THE LIST IS LOADING...
InstallationSuccess="@g%#INSTALLED SUCCESSFULLY!##CLICK ANYHWHERE TO CONTINUE"
Installing=INSTALLING %
InformationQuerying=QUERYING REPO INFO
# Max. 8 characters
ListRatingLabel=RATING
# Max. 8 characters
ListUpdateLabel=UPDATED
# Installed resourcepack load order setting
LoadPriority=LOAD PRIORITY
SortMode=SORT
# Max. 8 characters
SortByUpdate=UPDATED
# Max. 8 characters
SortByRating=RATING
NoPacksInstalled=NO RESOURCEPACKS ARE CURRENTLY INSTALLED.
PackDisabled=DISABLED
# Should be as short as possible
UpdatedLongAgo="LONG#AGO"
NewPackPromotion=NEW!
UpdatedJustNow=JUST NOW
UpdatedToday=TODAY
UpdatedYesterday=YESTERDAY
UpdatedRecently=RECENTLY
UpdatedThisWeek="THIS#WEEK"
UpdatedDaysAgo="% D.#AGO"
ErrorMissingFiles=MISSING RESOURCEPACK FILES
FullviewOpenGitHub=SEE GITHUB PAGE
ViewNoScreenshots=@dNO SCREENSHOTS :(
FullviewPackInfo=PACK INFO
FullviewCreationInfo=CREATED ON:
FullviewLastUpdate=LAST UPDATED:
FullviewInstallationDate=INSTALLED ON:
FullviewStars=STARS:
ButtonDownload=DOWNLOAD
ButtonDisable=DISABLE
ButtonEnable=ENABLE

[ControlOptions]
GamepadOn=КОНТРОЛЕР
GamepadStyle=СТИЛЬ КОНТРОЛЕРА
AimAssist=ДОНАВЕДЕННЯ
AutoAim=САМОНАВЕДЕННЯ
# Allows swapping and using abilities by pressing volume buttons
VolumeControls="КЕРУВАННЯ#ГУЧНІСТЮ"
# Split aim & fire into two separate control elements
SplitFireControls="РОЗДІЛЬНА#СТРІЛЬБА"
# Force player aim crosshair to be always visible
FixedSight=ФІКСОВАНИЙ ПРИЦІЛ
TouchControlScale=МАСШТАБ
Remap=МАКЕТ КЕРУВАННЯ
ResetTouchLayout=СКИНУТИ НАЛАШТУВАННЯ
SimpleTouchControls=СПРОЩЕНЕ
ButtonFire=СТРІЛЬБА
ButtonActive=ВМІННЯ
ButtonSwap=ЗМІНИТИ ЗБРОЮ
ButtonPick=ПІДБІР/ВЗАЄМОДІЯ
ButtonChat=ВІДКРИТИ ЧАТ
ButtonUp=ДОГОРИ
ButtonDown=ВНИЗ
ButtonLeft=НАЛІВО
ButtonRight=НАПРАВО
DebugOverlay=МЕНЮ ВІДЛАДКИ
ResetDefaults=СКИНУТИ НАЛАШТУВАННЯ

[R:Intro]
LoadGameFailure=Не вдалося завантажити збережену гру.
# The message is padded with newlines only as a stylistic choice, but automatic wordwrapping is supported.
ProjectDisclaimerText="@w###ЦЕЙ ПРОЄКТ - НЕОФІЦІЙНЕ ВІДТВОРЕННЯ#ГРИ СПІЛЬНОТОЮ, РОЗРОБНИК ЯКОГО ЖОДНИМ ЧИНОМ#НЕ ПОВ'ЯЗАНИЙ З @yVLAMBEER@w.##ВІН ПОШИРЮЄТЬСЯ БЕЗКОШТОВНО НА ПЛАТФОРМІ ITCH.IO#ТА МАЄ ВІДКРИТИЙ ВИХІДНИЙ КОД НА GITHUB##ЯКЩО ВИ ЗАПЛАТИЛИ КОШТИ ЗА ДОСТУП ДО ГРИ,#АБО НАТРАПИЛИ НА РЕКЛАМУ ВСЕРЕДИНІ ДОДАТКА,#РЕКОМЕНДОВАНО НЕГАЙНО ВИДАЛИТИ ЙОГО З ВАШОГО ПРИСТРОЮ"
ProjectDisclaimerTitle=УВАГА
DisclaimerContinue=НАТИСНІТЬ ЗАДЛЯ ПРОДОВЖЕННЯ
LoadGameYes=ТАК
LoadGameNo=НІ
LoadGameContinue=@sПРОДОВЖИТИ ЗБЕРЕЖЕНУ ГРУ?@w

[ResourcepackOptions]
DisclaimerText="RESOURCEPACKS ARE AN EXCLUSIVE FEATURE OF#NUCLEAR THRONE MOBILE.##A RESOURCEPACK IS A USER-CREATED ASSET COLLECTION (TEXTURES, SOUNDS, TEXT) FOR DECORATIVE PURPOSES ONLY, WITH NO GAMEPLAY BENEFITS.##RESOURCEPACK BROWSER, DESPITE BEING MODERATED,#MAY STILL CONTAIN QUESTIONABLE CONTENT.##THE DEVELOPER IS NOT LIABLE FOR ANY HARMFUL MATERIAL."
# Delay before the user is able to proceed to resourcepack options
DisclaimerProceedWait=@sPROCEED (%)
DisclaimerProceed=@yPROCEED
ResourcepackOptions=RESOURCEPACKS
ViewInstalled="ПЕРЕГЛЯНУТИ#ВСТАНОВЛЕНІ"
Browse=БРАУЗЕР
DirectDownload=ЗА ПОСИЛАННЯМ

[R:MainMenu]
AchievementHidden=ПРИХОВАНО
Achievements=ДОСЯГНЕННЯ
DiscordLink=JOIN OUR DISCORD!
RunHistory:daily=DAILY
RunHistory:weekly=WEEKLY
RunHistoryScoreAVG=@dSCORE AVG.
Leaderboards=ТАБЛИЦЯ ЛІДЕРІВ
MultiplayerTBA="MULTIPLAYER WILL BE AVAILABLE#IN FUTURE UPDATES"
CustomModeTBA="CUSTOM MODE WILL BE AVAILABLE#IN FUTURE UPDATES"
RunHistory=RUN HISTORY

[CharacterPrefOptions]
CharacterLocked=ЗАКРИТО
AutoTelekinesis=АВТО ТЕЛЕКІНЕЗ
AutoExplosions=АВТО ПІДРИВ
AutoSnare="ПІДСТВОЛЬНИЙ#ПАСТКОКИД"
PopPopToggle="ПЕРЕМИКАЧ#ПІФ-ПАФ-У"
DualWieldToggle="ОДНОЧАСНА#ПАЛЬБА"
UseWeaponWhenBeaming="ПІДСТВОЛЬНИЙ#ПРОМІНЬ"
SwipeBombing=ОБСТРІЛ СВАЙПОМ
GambleToggle=ПЕРЕМИКАЧ РУЛЕТКИ

[ProfileOptions]
ColorHEX=ЗМІНА КОЛЬОРУ
ColorSelectorNone=ЖОДНОГО
ColorRed=ЧЕРВОНИЙ
ColorGreen=ЗЕЛЕНИЙ
ColorBlue=СИНІЙ
ID=ID
IDCopied=@g[СКОПІЙОВАНО]
ProfileName=ІМ'Я ПРОФІЛЮ
ProfileNameInput=ENTER PROFILE NAME
ColorOptions=КОЛІР
ColorDefault=СКИНУТИ НАЛАШТУВАННЯ
DataOptions=ДАНІ

[Weapons]
# Electric Guitar isn't translated in the basegame as of right now
128:Name=ЕЛЕКТРОГІТАРА
# Electric Guitar also uses the same description as the regular Guitar. NTM simply just adds a little sprinkle of detail to it
128:Text=РИБА МОЖЕ В РОК-Н-РОЛ

[R:Stats]
# Important! Stat entries should be as short as possible.
# Total damage taken as Big Dog
Uniq13=ЗАЗНАНО ШКОДИ
# Skeleton's Blood gamble luck streak
Uniq14=РЕКОРД УДАЧІ
# Amount of gas produced by Frog
Uniq15=ОБ'ЄМ ГАЗУ

[CheatOptions]
# Developer debug overlay
Console=КОНСОЛЬ
# Unlimited skill selection range
GrillerMode=МУТА-ГРИЛЬ
# Player gets timed out for 45sec instead of dying
Practice=ПРАКТИКА

[GameOptions]
NativeCursor=ПЛАВНИЙ КУРСОР
MouseLock=ОБМЕЖЕННЯ КУРСОРУ
PauseButton=КНОПКА ПАУЗИ
AchievementPopups="СПОВІЩЕННЯ#ДОСЯГНЕНЬ"
ProfileOptions=ПРОФІЛЬ

[R:Unlock]
GenericRace="@w% РОЗБЛОКОВАНО#@s%"
GenericSkin="@w% %-СКІН РОЗБЛОКОВАНО#@s%"
Cheats="@wШАХРАЙСТВА РОЗБЛОКОВАНО#@sЗАВІТАЙТЕ У МЕНЮ НАЛАШТУВАНЬ!"

[Options]
CheatOptions=ШАХРАЙСТВА
CharacterPrefOptions=НАЛАШТУНКИ ПЕРСОНАЖІВ
ExperimentalOptions=ЕКСПЕРИМЕНТАЛЬНІ
ProfileOptions=ПРОФІЛЬ

[ExperimentalOptions]
KeyboardMode=РЕЖИМ КЛАВІАТУРИ
JoystickRegions="НЕФІКСОВАНІ#ДЖОЙСТИКИ"
HideJoysticks="ПРИХОВАТИ#ДЖОЙСТИКИ"

[VideoOptions]
WideScreen=ПОВНИЙ ЕКРАН
Bloom=СВІТІННЯ
Particles=ЧАСТИНКИ
DisplayOptions=НАЛАШТУНКИ ДИСПЛЕЮ

[Bosses]
# "GUN GOD's" name isn't translated in the base game as of right now
GunGod="БОГ#ЗБРОЇ"

[R:CoopLobby]
Host=СТВОРИТИ ГРУ
RemoteAddress=ОНОВИТИ СПИСОК
RemotePort=ПОРТ

[DataOptions]
OptionsReset=СКИНУТИ НАЛАШТУВАННЯ
ProgressReset=СКИНУТИ ПРОГРЕС

[R:Tips]
ContinuedRun=раді бачити вас знову!

[AudioOptions]
SoundsVolume=EFFECTS VOLUME

[R:MainMenu:Achievements]
Achievements=ДОСЯГНЕННЯ

[R:HUD]
PickUpAction=ПІДІБРАТИ

[R:GameOver]
Results=РЕЗУЛЬТАТ