# Last updated on 8 February 2026 at 18:43 GMT+3

[ResourcepackBrowser]
LoadingList=ЗАВАНТАЖЕННЯ СПИСКУ...
InstallationSuccess="@g%#УСПІШНО ВСТАНОВЛЕНО!##НАТИСНІТЬ БУДЬ-ДЕ ЗАДЛЯ ПРОДОВЖЕННЯ"
Installing=ВСТАНОВЛЕННЯ %
InformationQuerying=ЗАПИТ ІНФОРМАЦІЇ
# Max. 8 characters
ListRatingLabel=ОЦІНКА
# Max. 8 characters
ListUpdateLabel=ОНОВЛЕНО
# Installed resourcepack load order setting
LoadPriority=ПРІОРІТЕТ ЗАВАНТАЖЕННЯ
SortMode=СОРТУВАННЯ
# Max. 8 characters
SortByUpdate=ЗА ДАТОЮ
# Max. 8 characters
SortByRating=ЗА ВПОДОБАННЯМИ
NoPacksInstalled=НАРАЗІ НЕ ВСТАНОВЛЕНО ЖОДНОГО№ПАКЕТА РЕСУРСІВ.
PackDisabled=ВИМКНЕНО
# Should be as short as possible
UpdatedLongAgo=ДАВНО
NewPackPromotion=НОВЕ!
UpdatedJustNow=ЩОЙНО
UpdatedToday=СЬОГОДНІ
UpdatedYesterday=ВЧОРА
UpdatedRecently=НЕЩОДАВНО
UpdatedThisWeek="ЦЬОГО#ТИЖНЯ"
UpdatedDaysAgo="% ДН.#ТОМУ"
ErrorMissingFiles=ВІДСУТНІ ФАЙЛИ
FullviewOpenGitHub="ПЕРЕГЛЯНУТИ#СТОРІНКУ НА GITHUB"
ViewNoScreenshots=@dНЕМАЄ ЗОБРАЖЕНЬ :(
FullviewPackInfo="ІНФОРМАЦІЯ#ПРО ПАКЕТ"
FullviewCreationInfo=СТВОРЕНО:
FullviewLastUpdate=ОНОВЛЕНО:
FullviewInstallationDate=ВСТАНОВЛЕНО:
FullviewStars=ЗІРОК:
ButtonDownload=ЗАВАНТАЖИТИ
ButtonDisable=ВИМК
ButtonEnable=УВІМК

[R:Intro]
LoadGameFailure=Не вдалося завантажити збережену гру.
# The message is padded with newlines only as a stylistic choice, but automatic wordwrapping is supported.
ProjectDisclaimerText="@w###ЦЕЙ ПРОЄКТ - НЕОФІЦІЙНЕ ВІДТВОРЕННЯ#ГРИ СПІЛЬНОТОЮ, РОЗРОБНИК ЯКОГО ЖОДНИМ ЧИНОМ#НЕ ПОВ'ЯЗАНИЙ З @yVLAMBEER@w.##ВІН ПОШИРЮЄТЬСЯ БЕЗКОШТОВНО НА ПЛАТФОРМІ ITCH.IO#ТА МАЄ ВІДКРИТИЙ ВИХІДНИЙ КОД НА GITHUB##ЯКЩО ВИ ЗАПЛАТИЛИ КОШТИ ЗА ДОСТУП ДО ГРИ,#АБО НАТРАПИЛИ НА РЕКЛАМУ ВСЕРЕДИНІ ДОДАТКА,#РЕКОМЕНДОВАНО НЕГАЙНО ВИДАЛИТИ ЙОГО З ВАШОГО ПРИСТРОЮ"
ProjectDisclaimerExclamationsLeft=!!!
ProjectDisclaimerExclamationsRight=!!!
ProjectDisclaimerTitle=УВАГА
DisclaimerContinue=НАТИСНІТЬ ЗАДЛЯ ПРОДОВЖЕННЯ
LoadGameYes=ТАК
LoadGameNo=НІ
LoadGameContinue=@sПРОДОВЖИТИ ЗБЕРЕЖЕНУ ГРУ?@w

[ControlOptions]
GamepadOn=КОНТРОЛЕР
GamepadStyle=СТИЛЬ КОНТРОЛЕРА
AimAssist=ДОНАВЕДЕННЯ
AutoAim=САМОНАВЕДЕННЯ
# Allows swapping and using abilities by pressing volume buttons
VolumeControls="КЕРУВАННЯ#ГУЧНІСТЮ"
# Split aim & fire into two separate control elements
SplitFireControls="РОЗДІЛЬНА#СТРІЛЬБА"
# Force player aim crosshair to be always visible
FixedSight=ФІКСОВАНИЙ ПРИЦІЛ
TouchControlScale=МАСШТАБ
Remap=МАКЕТ КЕРУВАННЯ
ResetTouchLayout=СКИНУТИ НАЛАШТУВАННЯ
SimpleTouchControls=СПРОЩЕНЕ
ButtonFire=СТРІЛЬБА
ButtonActive=ВМІННЯ
ButtonSwap=ЗМІНИТИ ЗБРОЮ
ButtonPick=ПІДБІР/ВЗАЄМОДІЯ
ButtonChat=ВІДКРИТИ ЧАТ
ButtonUp=ДОГОРИ
ButtonDown=ВНИЗ
ButtonLeft=НАЛІВО
ButtonRight=НАПРАВО
DebugOverlay=МЕНЮ ВІДЛАДКИ
ResetDefaults=СКИНУТИ НАЛАШТУВАННЯ

[ResourcepackOptions]
# Delay before the user is able to proceed to resourcepack options
DisclaimerProceedWait=@sПОГОДИТИСЬ І ПРОДОВЖИТИ (%)
DisclaimerProceed=@yПОГОДИТИСЬ І ПРОДОВЖИТИ
DisclaimerText="ПАКЕТИ РЕСУРСІВ Є ЕКСКЛЮЗИВНИМИ#ДЛЯ МОБІЛЬНОЇ ВЕРСІЇ NUCLEAR THRONE##ВОНИ НАДАЮТЬ МОЖЛИВІСТЬ ЗМІНЮВАТИ РЕСУРСИ ГРИ(ТЕКСТУРИ, ЗВУКИ, ЛОКАЛІЗАЦІЇ)#ЗАДЛЯ НАДАННЯ ГРІ НОВИХ БАРВ БЕЗ ВТРУЧАННЯ У ІГРОВІ МЕХАНІКИ.##ПОПРИ МОДЕРАЦІЮ БРАУЗЕРУ ПАКЕТІВ РЕСУРСІВ,#У НЬОМУ МОЖЕ МІСТИТИСЯ ВМІСТ СУМНІВНОГО ХАРАКТЕРУ##РОЗРОБНИК НЕ НЕСЕ ЖОДНОЇ ВІДПОВІДАЛЬНОСТІ ЗА НЕПРИЙНЯТНІ МАТЕРІАЛИ, РОЗМІЩЕНІ В БРАУЗЕРІ."
ResourcepackOptions=RESOURCEPACKS
ViewInstalled="ПЕРЕГЛЯНУТИ#ВСТАНОВЛЕНІ"
Browse=БРАУЗЕР
DirectDownload=ЗА ПОСИЛАННЯМ

[R:MainMenu]
AchievementHidden=ПРИХОВАНО
Achievements=ДОСЯГНЕННЯ
DiscordLink=DISCORD-СПІЛЬНОТА!
RunHistory:daily=ЩОДЕННИЙ
RunHistory:weekly=ЩОТИЖНЕВИЙ
RunHistoryScoreAVG=@dСЕРЕДНІЙ РАХУНОК
Leaderboards=ТАБЛИЦЯ ЛІДЕРІВ
MultiplayerTBA="БАГАТОКОРИСТУВАЦЬКА ГРА#ЗНАХОДИТЬСЯ У СТАДІЇ РОЗРОБКИ"
CustomModeTBA="КОРИСТУВАЦЬКА ГРА#ЗНАХОДИТЬСЯ У СТАДІЇ РОЗРОБКИ"
RunHistory=РЕЗУЛЬТАТИ

[DataOptions]
OptionsResetDisclaimer="@wУВАГА!##@sЦЯ ДІЯ БЕЗПОВОРОТНО СКИНЕ#УСІ ВАШІ НАЛАШТУВАННЯ.###ВПЕВНЕНІ, ЩО БАЖАЄТЕ ПРОДОВЖИТИ?@w"
ProgressResetDisclaimer="@rУВАГА!!!##@sЦЯ ДІЯ ПОВНІСТЮ СКИНЕ ВАШ ПРОГРЕС:#УСІ ВАШІ ПЕРСОНАЖІ, ДОСЯГНЕННЯ ТА СТАТИСТИКА#БЕЗПОВОРОТНО АНУЛЮЮТЬСЯ###ВПЕВНЕНІ, ЩО БАЖАЄТЕ ПРОДОВЖИТИ?@w"
OptionsReset=СКИНУТИ НАЛАШТУВАННЯ
ProgressReset=СКИНУТИ ПРОГРЕС

[Tutorial]
Touch:1=WALK USING @wMOVEMENT STICK
Touch:2=PICK UP NEW WEAPON USING THE @wINTERACT BUTTON
Touch:3="AIM USING THE @wATTACK JOYSTICK@s#TOUCHING THEN RELEASING WILL FIRE"
Touch:4="SWAP WEAPONS USING THE @wSWAP BUTTON#TRY IT A FEW TIMES!"
Touch:5="@wABILITY BUTTON@s USES YOUR SPECIAL SKILL#@wGIVE IT A GO!"

[CharacterPrefOptions]
CharacterLocked=ЗАКРИТО
AutoTelekinesis=АВТО ТЕЛЕКІНЕЗ
AutoExplosions=АВТО ПІДРИВ
AutoSnare="ПІДСТВОЛЬНИЙ#ПАСТКОКИД"
PopPopToggle="ПЕРЕМИКАЧ#ПІФ-ПАФ-У"
DualWieldToggle="ОДНОЧАСНА#ПАЛЬБА"
UseWeaponWhenBeaming="ПІДСТВОЛЬНИЙ#ПРОМІНЬ"
SwipeBombing=ОБСТРІЛ СВАЙПОМ
GambleToggle=ПЕРЕМИКАЧ РУЛЕТКИ

[ProfileOptions]
ColorHEX=ЗМІНА КОЛЬОРУ
ColorSelectorNone=ЖОДНОГО
ColorRed=ЧЕРВОНИЙ
ColorGreen=ЗЕЛЕНИЙ
ColorBlue=СИНІЙ
ID=ID
IDCopied=@g[СКОПІЙОВАНО]
ProfileName=ІМ'Я ПРОФІЛЮ
ProfileNameInput=УВЕДІТЬ ІМ'Я ПРОФІЛЮ
ColorOptions=КОЛІР
ColorDefault=СКИНУТИ НАЛАШТУВАННЯ
DataOptions=ДАНІ

[Options]
Yes=ТАК
No=НІ
CheatOptions=ШАХРАЙСТВА
# Touch controls
TouchRemappingOptions=REMAPPING
# Keyboard/gamepad controls
KeyRemappingOptions=REMAPPING
CharacterPrefOptions=НАЛАШТУНКИ ПЕРСОНАЖІВ
ExperimentalOptions=ЕКСПЕРИМЕНТАЛЬНІ
ProfileOptions=ПРОФІЛЬ

[Weapons]
# Electric Guitar isn't translated in the basegame as of right now
128:Name=ЕЛЕКТРОГІТАРА
# Electric Guitar also uses the same description as the regular Guitar. NTM simply just adds a little sprinkle of detail to it
128:Text=РИБА МОЖЕ В РОК-Н-РОЛ

[R:Stats]
# Important! Stat entries should be as short as possible.
# Total damage taken as Big Dog
Uniq13=ЗАЗНАНО ШКОДИ
# Skeleton's Blood gamble luck streak
Uniq14=РЕКОРД УДАЧІ
# Amount of gas produced by Frog
Uniq15=ОБ'ЄМ ГАЗУ

[CheatOptions]
# Developer debug overlay
Console=КОНСОЛЬ
# Unlimited skill selection range
GrillerMode=МУТА-ГРИЛЬ
# Player gets timed out for 45sec instead of dying
Practice=ПРАКТИКА

[GameOptions]
NativeCursor=ПЛАВНИЙ КУРСОР
MouseLock=ОБМЕЖЕННЯ КУРСОРУ
PauseButton=КНОПКА ПАУЗИ
AchievementPopups="СПОВІЩЕННЯ#ДОСЯГНЕНЬ"
ProfileOptions=ПРОФІЛЬ

[R:Unlock]
GenericRace="@w% РОЗБЛОКОВАНО#@s%"
GenericSkin="@w% %-СКІН РОЗБЛОКОВАНО#@s%"
Cheats="@wШАХРАЙСТВА РОЗБЛОКОВАНО#@sЗАВІТАЙТЕ У МЕНЮ НАЛАШТУВАНЬ!"

[ExperimentalOptions]
KeyboardMode=РЕЖИМ КЛАВІАТУРИ
JoystickRegions="НЕФІКСОВАНІ#ДЖОЙСТИКИ"
HideJoysticks="ПРИХОВАТИ#ДЖОЙСТИКИ"

[PauseMenu]
RunSavingTip="YOU CAN SAVE AND CONTINUE THIS RUN LATER#IF YOU EXIT WITHOUT QUITTING TO MAIN MENU"

[VideoOptions]
WideScreen=ПОВНИЙ ЕКРАН
Bloom=СВІТІННЯ
Particles=ЧАСТИНКИ
DisplayOptions=НАЛАШТУНКИ ДИСПЛЕЮ

[Bosses]
# "GUN GOD's" name isn't translated in the base game as of right now
GunGod="БОГ#ЗБРОЇ"

[MonthNameShort]
1=JAN
2=FEB
3=MAR
4=APR
5=MAY
6=JUN
7=JUL
8=AUG
9=SEP
10=OCT
11=NOV
12=DEC

[R:CoopLobby]
Host=СТВОРИТИ ГРУ
RemoteAddress=ОНОВИТИ СПИСОК
RemotePort=ПОРТ

[R:Tips]
ContinuedRun=раді бачити вас знову!

[AudioOptions]
SoundsVolume=ГУЧНІСТЬ ЕФЕКТІВ

[R:MainMenu:Achievements]
Achievements=ДОСЯГНЕННЯ

[R:HUD]
PickUpAction=ПІДІБРАТИ

[R:GameOver]
Results=РЕЗУЛЬТАТ