instance_create((x - 32), y, PortalClear)
instance_create((x + 32), y, PortalClear)
instance_create(x, (y + 32), PortalClear)
instance_create(x, (y - 32), PortalClear)
instance_create(x, y, Van)
snd_play(sndVanPortal)