raddrop = 25
max_hp = 45
meleedamage = 20
size = 2
spr_idle = sprLightningCrystalIdle
spr_walk = sprLightningCrystalIdle
spr_hurt = sprLightningCrystalHurt
spr_dead = sprLightningCrystalDead
event_inherited()
spr_fire = sprLightningCrystalFire
snd_hurt = sndLightningCrystalHit
snd_dead = sndLightningCrystalDeath
hitid = HitId.LightningCrystal
ammo = 4
explode = 0
gunangle = random_angle
spr_shadow_y = 4
alarm[1] = (50 + random(90))
hitid = HitId.LightningCrystal