function Resourcepack(_name) constructor {
	
	static __default_description = "No extra information provided. This is	a template file generated by the game."
	
	// basic fields
	self[$ "id"] = _name
	
	name = _name
	descriptionShort = ""
	description = ""
	
	full_name = _name
	owner = "unknown"
	stars = 0
	priority = 0
	hasIcon = false
	
	// time fields
	created = 0
	updated = 0
	installtime = 0
	
	// control fields
	promoted = false
	loaded = false
	external = false
	
	/// @function setup_default_fields
	static setup_default_fields = function() {
		owner = scrSavedataGetUsername()
		descriptionShort = owner + "'s resourcepack"
		description = __default_description
		full_name = "local/" + string(self[$ "id"])
		created = unix_timestamp()
		updated = created
		installtime = updated
	}
	
	/// @function define_sources
	/// @param id
	/// @param installation_path
	/// @param is_externally_sourced
	static define_sources = function(_id, _pack_directory, _is_external) {
		self[$ "id"] = _id
		path = _pack_directory
		external = _is_external
		hasIcon = file_exists(_pack_directory + "icon.png")
	}
	
	/// @function load_pack_meta_from_struct
	static load_pack_meta_from_struct = function(_struct) {
		if (is_string(_struct[$ "name"])) {
			name = _struct.name
		}
		if (is_string(_struct[$ "descriptionShort"])) {
			descriptionShort = _struct.descriptionShort
		}
		if (is_string(_struct[$ "description"])) {
			description = _struct.description
		}
	}
	
	/// @function load_resourcepackbrowser_data_from_struct
	static load_resourcepackbrowser_data_from_struct = function(_struct) {
		print("loadin bro", json_stringify(_struct, true))
		
		full_name = _struct[$ "full_name"] ?? full_name
		owner = _struct[$ "owner"] ?? owner
		created = _struct[$ "created"] ?? created
		updated = _struct[$ "updated"] ?? updated
		installtime = _struct[$ "installtime"] ?? installtime
		stars = _struct[$ "stars"] ?? 0
		priority = _struct[$ "priority"] ?? 0
	}
	
	//
	version_major = resourcepack_format_version_major
	version_minor = resourcepack_format_version_minor
	
	static get_format_version = function() {
		return $"{version_major}.{version_minor}"
	}
}